const addFooter = () => {
  const mainContainer = document.getElementById('viki-main-container');
  if (!mainContainer) {
    setTimeout(() => {
      addFooter();
    }, 200);
  } else {
    if (window.location.hash)
      document.body.innerHTML += `<footer class="viki-footer text-muted"><div class="container-fluid p-3 p-md-5"><p class="viki-footer-row">Past, Present, and Future.<br><a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png"></a>除特殊标注外，本站采用<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">知识共享署名-非商业性使用-相同方式共享 4.0 国际许可协议</a>进行许可。<br>Made with ❤️ by Matrew File(&<a href="https://pwp.app/">BackRunner</a>).</p><p class="viki-footer-row viki-footer-viki">Generated by <em><a href="https://tamlok.github.io/viki/">Viki</a></em>.</p></div></footer>`;
  }
}

window.addEventListener('load', addFooter);